### ISSUE TITLE
1.7.0 Update ruined the theme?

### ISSUE THREAD

**Issue by raidermax** [lots0logs/Numix-Frost#1]
I am not sure either if this is due to the arch AUR maintainer, or the Antergos repo maintainer as those are two possible variables. I updated my system to numix-frost-themes 1.7.0 and it ended up removing the themes, or at l least many aspects in it. Everything is layed out as if it were using Adwaita.

I am not the only one experiencing this either, I went to https://scrollback.io/numix/all/all-messages?ds=%257B%257D and I found another who updated that got their themes messed up and they were on Ubuntu 15.04

**Comment by lots0logs** [comment]
I cannot speak to the Ubuntu user. Though for our package, users need to simply reselect the themes using their DE's configuration tools (Gnome=Tweak Tool, Cinnamon=System Settings, etc). There was a message output after the package update was installed that informed users of this. I apologize for the inconvenience.

**Comment by raidermax** [comment]
Why did you close this, the issue still persists? I already reselected the themes MULTIPLE times and logged out/in and even restarted the machine and the same problems persist. Although you are saying "your package", problem is I am downloading the package that was made by maintainers of Antergos distro....so maybe the problem lies with them?

**Comment by lots0logs** [comment]
I am the one of the Antergos Developers. I maintain this package for antergos. What Desktop Environment are you using? What steps did you take to configure the themes  and did you use the new name (hyphens instead of spaces: `Numix-Frost` & `Numix-Frost-Light`)

**Comment by raidermax** [comment]
Alright so, I am using Cinnamon and as of now, I have removed any type of numix-theme that was on my system. I started with installing numix-themes from the arch community repo (having this installed or not installed doesnt seem to affect anything). I then tried manually building numix-frost-themes and also using yaourt (gave same response, which was a good one, in this case I guess refreshing all the files fixed my problem as the theme is showing up correctly except in other apps, I will further discuss). Here are how I have my settings in cinnamon, http://gyazo.com/6790487c04ec74900dbb2a65fb3badb6 (for some reason numix-frost-light has the regular numix window border in the picture but on DE it doesnt....which is what I want)

So the numix-frost-theme is now showing up correctly, Nemo and cinnamon related settings are themed nicely, pretty much cinnamon related things are fine...however if I open up Firefox, mumble, Filezilla, libreoffice, Audacity, the list goes on, the window title border is a different color than the rest of the window. Here are some examples,

http://gyazo.com/a1c6c0aea9a3ba4e584e1449881aa5ea (window is selected)
http://gyazo.com/950f3c9401e1424975eb13957e972d5a (window is selected)

This did not occur before which is strange.

**Comment by lots0logs** [comment]
Okay, thanks for the details. The window titlebar color mis-match is a new bug that I hadn't noticed in my testing. I've added it to the issues list (#2) and will try to get a fix pushed out later today or tomorrow. Cheers!

**Comment by raidermax** [comment]
Ahh thank you so much! I was thinking it would end being a bug that was very difficult to solve but you seem to know what the issue is already.

Thank you for your very quick and efficient "customer support" and I appreciate you for maintaining this really. Numix is the only theme I like on linux and its kept me staying on it. Thanks again and have a nice day!

**Comment by lots0logs** [comment]
You're welcome :smile:
